
#App
spring.application.name=chatapp
server.port=8080

# AWS
aws.region=eu-west-1
aws.access-key-id=dummy
aws.secret-access-key=dummysecret

# DynamoDB Local
aws.dynamodb.endpoint=http://localhost:8000

# S3 / MinIO Local
aws.s3.endpoint=http://localhost:9000
aws.s3.bucket-name=chatapp-profiles

# Thymeleaf
spring.thymeleaf.cache=false